baseUrl=https://reqres.in/api
email=eve.holt@reqres.in
password=test
wrongPassword=wrong
#xApiKey=reqres_8610f289dada46deb8611130b80ba208
xApiKey=reqres_100381e8bca7482ba2b63acc34ded5ad
targetUserId=2
targetUserIdNotFound=23
expectedDomain=reqres.in